[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
math_lib = { path = "../math_lib" }

[dev-dependencies]
rand_chacha = "0.9.0-alpha.1"
rand = "0.9.0-alpha.1"
test-case = "3.3.1"