[package]
name = "profiling"
version = "0.1.0"
edition = "2021"

[dependencies]
math_lib = { path = "../math_lib" }
rand = "0.9.0-alpha.1"

[profile.release]
debug = true

[profile.bench]
debug = true
